#!/usr/bin/env bash

unset GIT_LITERAL_PATHSPECS

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

if git diff --cached $against | grep -e '/Users' -e '/home' -e 'C:/' >/dev/null 2>&1
then
    cat <<\EOF
Error: Attempt to add reference to absolute path.

This path may not be resolvable on another machine.
Make the path relative to the project instead.
EOF
    exit 1
fi

if git diff --cached $against 'hardware/*kicad_sch' | grep 'reference.*\?' > /dev/null 2>&1
then
    cat <<\EOF
Error: Attempt to add unannotated part

Make sure to add reference designators to all parts in the schematic.
EOF
    exit 1
fi
